name: TaifiOS
options:
  bundleIdPrefix: com.taif
targets:
  TaifiOS:
    type: application
    platform: iOS
    deploymentTarget: "15.0"
    sources: 
      - TaifiOS
    settings:
      INFOPLIST_FILE: TaifiOS/Info.plist
    dependencies:
      - target: TaifKeyboardExtension
  TaifKeyboardExtension:
    type: app-extension
    platform: iOS
    deploymentTarget: "15.0"
    sources: 
      - TaifKeyboardExtension
      - TaifiOS/SettingsManager.swift
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.taif.TaifiOS.TaifKeyboardExtension
      INFOPLIST_FILE: TaifKeyboardExtension/Info.plist
